// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function optionsToJs(param) {
  return {
          framework: param[/* framework */0]
        };
}

function optionsFromJs(param) {
  return /* record */[/* framework */param.framework];
}

var uIKit = /* UIKit */0;

var appKit = /* AppKit */1;

exports.uIKit         = uIKit;
exports.appKit        = appKit;
exports.optionsToJs   = optionsToJs;
exports.optionsFromJs = optionsFromJs;
/* No side effect */
