// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var Ast = 0;

var Render = 0;

var Color = 0;

exports.Ast    = Ast;
exports.Render = Render;
exports.Color  = Color;
/* No side effect */
