// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List                       = require("bs-platform/lib/js/list.js");
var Block                      = require("bs-platform/lib/js/block.js");
var Pervasives                 = require("bs-platform/lib/js/pervasives.js");
var XmlRender$LonaCompilerCore = require("./xmlRender.bs.js");

function join(sep, param) {
  if (param) {
    var tl = param[1];
    if (tl) {
      return Pervasives.$at(/* :: */[
                  param[0],
                  /* :: */[
                    sep,
                    /* [] */0
                  ]
                ], join(sep, tl));
    } else {
      return param;
    }
  } else {
    return param;
  }
}

function render(colors) {
  var colorDoc = function (color) {
    var match = color[/* comment */3];
    return Pervasives.$at(match ? /* :: */[
                  /* Comment */Block.__(4, [match[0]]),
                  /* [] */0
                ] : /* [] */0, /* :: */[
                /* Element */Block.__(3, [{
                      tag: "color",
                      attributes: /* :: */[
                        /* Attribute */Block.__(5, [{
                              name: "name",
                              value: color[/* id */0]
                            }]),
                        /* [] */0
                      ],
                      content: /* :: */[
                        /* CharData */Block.__(6, [color[/* value */2]]),
                        /* [] */0
                      ]
                    }]),
                /* [] */0
              ]);
  };
  return XmlRender$LonaCompilerCore.toString(/* Document */Block.__(0, [{
                  prolog: /* Prolog */Block.__(1, [{
                        xmlDecl: /* Some */[/* XMLDecl */Block.__(2, [{
                                version: "1.0",
                                encoding: /* Some */["utf-8"]
                              }])]
                      }]),
                  element: /* Element */Block.__(3, [{
                        tag: "resources",
                        attributes: /* [] */0,
                        content: List.concat(join(/* :: */[
                                  /* Empty */0,
                                  /* [] */0
                                ], List.map(colorDoc, colors)))
                      }])
                }]));
}

exports.join   = join;
exports.render = render;
/* XmlRender-LonaCompilerCore Not a pure module */
