disabled_rules:
  - block_based_kvo
  - variable_name
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - type_body_length
  - force_cast
  - force_try
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - line_length
  - large_tuple
  - shorthand_operator
  - todo

included:
  - LonaStudio
