// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List                      = require("bs-platform/lib/js/list.js");
var $$Array                   = require("bs-platform/lib/js/array.js");
var Curry                     = require("bs-platform/lib/js/curry.js");
var Prettier$LonaCompilerCore = require("./prettier.bs.js");

function indentLine(amount, line) {
  return " ".repeat(amount) + line;
}

function flatMap(f, list) {
  if (list) {
    var head = list[0];
    if (head) {
      return /* :: */[
              head[0],
              flatMap(f, list[1])
            ];
    } else {
      return /* [] */0;
    }
  } else {
    return /* [] */0;
  }
}

function join(sep, items) {
  return $$Array.of_list(items).join(sep);
}

var $$String = /* module */[/* join */join];

function prefixAll(sep, items) {
  return Curry._1(Prettier$LonaCompilerCore.Doc[/* Builders */0][/* concat */2], List.map((function (x) {
                    return Curry._2(Prettier$LonaCompilerCore.Doc[/* Builders */0][/* <+> */5], sep, x);
                  }), items));
}

function renderOptional(render, item) {
  if (item) {
    return Curry._1(render, item[0]);
  } else {
    return Prettier$LonaCompilerCore.Doc[/* Builders */0][/* empty */1];
  }
}

exports.indentLine     = indentLine;
exports.flatMap        = flatMap;
exports.$$String       = $$String;
exports.prefixAll      = prefixAll;
exports.renderOptional = renderOptional;
/* Prettier-LonaCompilerCore Not a pure module */
