# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS
  target 'iOSUITests' do
    inherit! :search_paths
    
    # Pods for testing
    pod 'EyesImages'
  end

end

target 'MacOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MacOS
end
