// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function optionsToJs(param) {
  return {
          preset: param[/* preset */0]
        };
}

function optionsFromJs(param) {
  return /* record */[/* preset */param.preset];
}

var standard = /* Standard */0;

var airbnb = /* Airbnb */1;

exports.standard      = standard;
exports.airbnb        = airbnb;
exports.optionsToJs   = optionsToJs;
exports.optionsFromJs = optionsFromJs;
/* No side effect */
