// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function reference(param_0) {
  return /* Reference */Block.__(0, [param_0]);
}

function named(param_0, param_1) {
  return /* Named */Block.__(1, [
            param_0,
            param_1
          ]);
}

function $$function(param_0, param_1) {
  return /* Function */Block.__(2, [
            param_0,
            param_1
          ]);
}

function referenceFromJs(ltype) {
  switch (ltype.tag | 0) {
    case 0 : 
        return /* Some */[ltype[0]];
    case 1 : 
    case 2 : 
        return /* None */0;
    
  }
}

var stringType = /* Reference */Block.__(0, ["String"]);

var colorType = /* Named */Block.__(1, [
    "Color",
    stringType
  ]);

var textStyleType = /* Named */Block.__(1, [
    "TextStyle",
    stringType
  ]);

var urlType = /* Named */Block.__(1, [
    "URL",
    stringType
  ]);

function parameterToJs(param) {
  return {
          name: param[/* name */0],
          ltype: param[/* ltype */1],
          defaultValue: param[/* defaultValue */2]
        };
}

function parameterFromJs(param) {
  return /* record */[
          /* name */param.name,
          /* ltype */param.ltype,
          /* defaultValue */param.defaultValue
        ];
}

function layerTypeToString(x) {
  if (typeof x === "number") {
    switch (x) {
      case 0 : 
          return "View";
      case 1 : 
          return "Text";
      case 2 : 
          return "Image";
      case 3 : 
          return "Animation";
      case 4 : 
          return "Children";
      case 5 : 
          return "Unknown";
      
    }
  } else {
    return x[0];
  }
}

var undefinedType = /* Reference */Block.__(0, ["Undefined"]);

var booleanType = /* Reference */Block.__(0, ["Boolean"]);

var numberType = /* Reference */Block.__(0, ["Number"]);

var handlerType = /* Function */Block.__(2, [
    /* [] */0,
    /* Reference */Block.__(0, ["Undefined"])
  ]);

exports.reference         = reference;
exports.named             = named;
exports.$$function        = $$function;
exports.undefinedType     = undefinedType;
exports.referenceFromJs   = referenceFromJs;
exports.booleanType       = booleanType;
exports.numberType        = numberType;
exports.stringType        = stringType;
exports.colorType         = colorType;
exports.textStyleType     = textStyleType;
exports.urlType           = urlType;
exports.handlerType       = handlerType;
exports.parameterToJs     = parameterToJs;
exports.parameterFromJs   = parameterFromJs;
exports.layerTypeToString = layerTypeToString;
/* No side effect */
