// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var stringType = /* Reference */Block.__(0, ["String"]);

var colorType = /* Named */Block.__(1, [
    "Color",
    stringType
  ]);

var textStyleType = /* Named */Block.__(1, [
    "TextStyle",
    stringType
  ]);

var urlType = /* Named */Block.__(1, [
    "URL",
    stringType
  ]);

var undefinedType = /* Reference */Block.__(0, ["Undefined"]);

var booleanType = /* Reference */Block.__(0, ["Boolean"]);

var numberType = /* Reference */Block.__(0, ["Number"]);

var handlerType = /* Function */Block.__(2, [
    /* [] */0,
    /* Reference */Block.__(0, ["Undefined"])
  ]);

exports.undefinedType = undefinedType;
exports.booleanType   = booleanType;
exports.numberType    = numberType;
exports.stringType    = stringType;
exports.colorType     = colorType;
exports.textStyleType = textStyleType;
exports.urlType       = urlType;
exports.handlerType   = handlerType;
/* No side effect */
